// Generated by gencpp from file yhs_can_msgs/bms_Infor_fb.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_BMS_INFOR_FB_H
#define YHS_CAN_MSGS_MESSAGE_BMS_INFOR_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct bms_Infor_fb_
{
  typedef bms_Infor_fb_<ContainerAllocator> Type;

  bms_Infor_fb_()
    : bms_Infor_voltage(0.0)
    , bms_Infor_current(0.0)
    , bms_Infor_remaining_capacity(0.0)  {
    }
  bms_Infor_fb_(const ContainerAllocator& _alloc)
    : bms_Infor_voltage(0.0)
    , bms_Infor_current(0.0)
    , bms_Infor_remaining_capacity(0.0)  {
  (void)_alloc;
    }



   typedef float _bms_Infor_voltage_type;
  _bms_Infor_voltage_type bms_Infor_voltage;

   typedef float _bms_Infor_current_type;
  _bms_Infor_current_type bms_Infor_current;

   typedef float _bms_Infor_remaining_capacity_type;
  _bms_Infor_remaining_capacity_type bms_Infor_remaining_capacity;





  typedef boost::shared_ptr< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> const> ConstPtr;

}; // struct bms_Infor_fb_

typedef ::yhs_can_msgs::bms_Infor_fb_<std::allocator<void> > bms_Infor_fb;

typedef boost::shared_ptr< ::yhs_can_msgs::bms_Infor_fb > bms_Infor_fbPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::bms_Infor_fb const> bms_Infor_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator2> & rhs)
{
  return lhs.bms_Infor_voltage == rhs.bms_Infor_voltage &&
    lhs.bms_Infor_current == rhs.bms_Infor_current &&
    lhs.bms_Infor_remaining_capacity == rhs.bms_Infor_remaining_capacity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8203058d8d76262b68aad3736466287";
  }

  static const char* value(const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8203058d8d76262ULL;
  static const uint64_t static_value2 = 0xb68aad3736466287ULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/bms_Infor_fb";
  }

  static const char* value(const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 bms_Infor_voltage\n"
"float32 bms_Infor_current\n"
"float32 bms_Infor_remaining_capacity\n"
;
  }

  static const char* value(const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bms_Infor_voltage);
      stream.next(m.bms_Infor_current);
      stream.next(m.bms_Infor_remaining_capacity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bms_Infor_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::bms_Infor_fb_<ContainerAllocator>& v)
  {
    s << indent << "bms_Infor_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.bms_Infor_voltage);
    s << indent << "bms_Infor_current: ";
    Printer<float>::stream(s, indent + "  ", v.bms_Infor_current);
    s << indent << "bms_Infor_remaining_capacity: ";
    Printer<float>::stream(s, indent + "  ", v.bms_Infor_remaining_capacity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_BMS_INFOR_FB_H
