// Generated by gencpp from file yhs_can_msgs/Drive_MCUEcoder_fb.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_DRIVE_MCUECODER_FB_H
#define YHS_CAN_MSGS_MESSAGE_DRIVE_MCUECODER_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct Drive_MCUEcoder_fb_
{
  typedef Drive_MCUEcoder_fb_<ContainerAllocator> Type;

  Drive_MCUEcoder_fb_()
    : Drive_fb_MCUEcoder(0)  {
    }
  Drive_MCUEcoder_fb_(const ContainerAllocator& _alloc)
    : Drive_fb_MCUEcoder(0)  {
  (void)_alloc;
    }



   typedef int32_t _Drive_fb_MCUEcoder_type;
  _Drive_fb_MCUEcoder_type Drive_fb_MCUEcoder;





  typedef boost::shared_ptr< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> const> ConstPtr;

}; // struct Drive_MCUEcoder_fb_

typedef ::yhs_can_msgs::Drive_MCUEcoder_fb_<std::allocator<void> > Drive_MCUEcoder_fb;

typedef boost::shared_ptr< ::yhs_can_msgs::Drive_MCUEcoder_fb > Drive_MCUEcoder_fbPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::Drive_MCUEcoder_fb const> Drive_MCUEcoder_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator2> & rhs)
{
  return lhs.Drive_fb_MCUEcoder == rhs.Drive_fb_MCUEcoder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48c12cfe499ba073506e85df7bf8a401";
  }

  static const char* value(const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48c12cfe499ba073ULL;
  static const uint64_t static_value2 = 0x506e85df7bf8a401ULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/Drive_MCUEcoder_fb";
  }

  static const char* value(const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Drive_fb_MCUEcoder\n"
;
  }

  static const char* value(const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Drive_fb_MCUEcoder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Drive_MCUEcoder_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::Drive_MCUEcoder_fb_<ContainerAllocator>& v)
  {
    s << indent << "Drive_fb_MCUEcoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Drive_fb_MCUEcoder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_DRIVE_MCUECODER_FB_H
