// Generated by gencpp from file yhs_can_msgs/io_fb.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_IO_FB_H
#define YHS_CAN_MSGS_MESSAGE_IO_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct io_fb_
{
  typedef io_fb_<ContainerAllocator> Type;

  io_fb_()
    : io_fb_enable(false)
    , io_fb_upper_beam_headlamp(false)
    , io_fb_turn_lamp(0)
    , io_fb_braking_lamp(false)
    , io_fb_speaker(false)
    , io_fb_fm_impact_sensor(false)
    , io_fb_rm_impact_sensor(false)  {
    }
  io_fb_(const ContainerAllocator& _alloc)
    : io_fb_enable(false)
    , io_fb_upper_beam_headlamp(false)
    , io_fb_turn_lamp(0)
    , io_fb_braking_lamp(false)
    , io_fb_speaker(false)
    , io_fb_fm_impact_sensor(false)
    , io_fb_rm_impact_sensor(false)  {
  (void)_alloc;
    }



   typedef uint8_t _io_fb_enable_type;
  _io_fb_enable_type io_fb_enable;

   typedef uint8_t _io_fb_upper_beam_headlamp_type;
  _io_fb_upper_beam_headlamp_type io_fb_upper_beam_headlamp;

   typedef int8_t _io_fb_turn_lamp_type;
  _io_fb_turn_lamp_type io_fb_turn_lamp;

   typedef uint8_t _io_fb_braking_lamp_type;
  _io_fb_braking_lamp_type io_fb_braking_lamp;

   typedef uint8_t _io_fb_speaker_type;
  _io_fb_speaker_type io_fb_speaker;

   typedef uint8_t _io_fb_fm_impact_sensor_type;
  _io_fb_fm_impact_sensor_type io_fb_fm_impact_sensor;

   typedef uint8_t _io_fb_rm_impact_sensor_type;
  _io_fb_rm_impact_sensor_type io_fb_rm_impact_sensor;





  typedef boost::shared_ptr< ::yhs_can_msgs::io_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::io_fb_<ContainerAllocator> const> ConstPtr;

}; // struct io_fb_

typedef ::yhs_can_msgs::io_fb_<std::allocator<void> > io_fb;

typedef boost::shared_ptr< ::yhs_can_msgs::io_fb > io_fbPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::io_fb const> io_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::io_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::io_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::io_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::io_fb_<ContainerAllocator2> & rhs)
{
  return lhs.io_fb_enable == rhs.io_fb_enable &&
    lhs.io_fb_upper_beam_headlamp == rhs.io_fb_upper_beam_headlamp &&
    lhs.io_fb_turn_lamp == rhs.io_fb_turn_lamp &&
    lhs.io_fb_braking_lamp == rhs.io_fb_braking_lamp &&
    lhs.io_fb_speaker == rhs.io_fb_speaker &&
    lhs.io_fb_fm_impact_sensor == rhs.io_fb_fm_impact_sensor &&
    lhs.io_fb_rm_impact_sensor == rhs.io_fb_rm_impact_sensor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::io_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::io_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::io_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::io_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::io_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7701f76c958e58d5738d208d5c0933cf";
  }

  static const char* value(const ::yhs_can_msgs::io_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7701f76c958e58d5ULL;
  static const uint64_t static_value2 = 0x738d208d5c0933cfULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/io_fb";
  }

  static const char* value(const ::yhs_can_msgs::io_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  io_fb_enable\n"
"bool  io_fb_upper_beam_headlamp\n"
"int8  io_fb_turn_lamp\n"
"bool  io_fb_braking_lamp\n"
"bool  io_fb_speaker\n"
"bool  io_fb_fm_impact_sensor\n"
"bool  io_fb_rm_impact_sensor\n"
;
  }

  static const char* value(const ::yhs_can_msgs::io_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.io_fb_enable);
      stream.next(m.io_fb_upper_beam_headlamp);
      stream.next(m.io_fb_turn_lamp);
      stream.next(m.io_fb_braking_lamp);
      stream.next(m.io_fb_speaker);
      stream.next(m.io_fb_fm_impact_sensor);
      stream.next(m.io_fb_rm_impact_sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct io_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::io_fb_<ContainerAllocator>& v)
  {
    s << indent << "io_fb_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_enable);
    s << indent << "io_fb_upper_beam_headlamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_upper_beam_headlamp);
    s << indent << "io_fb_turn_lamp: ";
    Printer<int8_t>::stream(s, indent + "  ", v.io_fb_turn_lamp);
    s << indent << "io_fb_braking_lamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_braking_lamp);
    s << indent << "io_fb_speaker: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_speaker);
    s << indent << "io_fb_fm_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fm_impact_sensor);
    s << indent << "io_fb_rm_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rm_impact_sensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_IO_FB_H
